### ISSUE TITLE
SwitchPinger_ping assertion: [Checksum.h:65] [(!((uintptr_t)buffer % 2))]

### ISSUE THREAD

**Issue by lgierth** [cjdelisle/cjdns#639]
Same nodes as in #638, all this is on A.

```
$ ./contrib/python/cexec 'InterfaceController_peerStats(0)'
{'peers': [{'last': 1408403068546, 'receivedOutOfRange': 0, 'bytesOut': 292335, 'duplicates': 0, 'switchLabel': '0000.0000.0000.0013', 'publicKey': 'vsbxsthgml9l7wxyqn1b9nc2c9cucbmdps0fh3gd2jn9ys017590.k', 'state': 'ESTABLISHED', 'lostPackets': 6, 'isIncoming': 0, 'bytesIn': 287440}], 'total': 1, 'txid': '2J5DZKPV3U'}
$ ./contrib/python/cexec 'SwitchPinger_ping("0000.0000.0000.0013")'
```

```
Assertion failure [Checksum.h:65] [(!((uintptr_t)buffer % 2))]

Program received signal SIGABRT, Aborted.
---Type <return> to continue, or q <return> to quit---
[Switching to Thread 0x7ffff7fd0740 (LWP 13874)]
0x00007ffff7624f89 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7624f89 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff7628398 in __GI_abort () at abort.c:89
#2  0x0000555555559867 in Assert_failure (format=0x5555555e2210 "Assertion failure [%s:%d] [%s]\n") at util/Assert.c:32
#3  0x000055555559f75b in Checksum_engine (buffer=0x55555588d739 "", length=25) at ./util/Checksum.h:65
#4  0x000055555559ffa3 in sendPing (data=0x55555588af48, sendPingContext=0x55555588b568) at net/SwitchPinger.c:166
#5  0x000055555557ed31 in asyncSendPing (vping=0x55555588ae68) at util/Pinger.c:92
#6  0x0000555555560ad3 in handleEvent (handle=0x55555588b3b8, status=0) at util/events/libuv/Timeout.c:47
#7  0x00005555555d67c1 in uv__run_timers (loop=loop@entry=0x5555557ff2b0) at ../src/unix/timer.c:146
#8  0x00005555555ccdc2 in uv_run (loop=0x5555557ff2b0, mode=UV_RUN_DEFAULT) at ../src/unix/core.c:275
#9  0x000055555555e5e9 in EventBase_beginLoop (eventBase=0x5555557ff268) at util/events/libuv/EventBase.c:83
#10 0x00005555555b7a75 in Core_main (argc=3, argv=0x7fffffffe568) at admin/angel/Core.c:502
#11 0x00005555555bb81f in main (argc=3, argv=0x7fffffffe568) at admin/angel/cjdroute2.c:447
(gdb) quit
```

**Comment by lgierth** [comment]
Never seen this happen again
