### ISSUE TITLE
Not compiling on OS X 

### ISSUE THREAD

**Issue by iShift** [cjdelisle/cjdns#746]
In file included from admin/angel/cjdroute2.c:15:
In file included from ./admin/Admin.h:20:
In file included from ./interface/addressable/AddrInterface.h:18:
In file included from ./interface/Interface.h:20:
In file included from ./wire/Message.h:23:
./util/Endian.h:52:22: error: token is not a valid binary operator in a preprocessor subexpression
    #if __GNUC_PREREQ(4, 8)
        ~~~~~~~~~~~~~^
1 error generated.

    at error (/Users/Shift/Desktop/cjdns/node_build/builder.js:52:15)
    at /Users/Shift/Desktop/cjdns/node_build/builder.js:115:22
    at /Users/Shift/Desktop/cjdns/node_build/builder.js:85:13
    at ChildProcess.<anonymous> (/Users/Shift/Desktop/cjdns/node_build/Semaphore.js:7:30)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

**Comment by koalalorenzo** [comment]
Same problem here

**Comment by benhylau** [comment]
:watch:-ing

**Comment by koalalorenzo** [comment]
By building it today, it seems to work fine for me :+1:

**Comment by iShift** [comment]
it seems to work fine for me too ..
